# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c65306e24998735286e272a38192104165a6ae0a70d0c63ef128663c690b5fccdadfce0c8778d971d263f03fdd01289b01666cb432dec8d5536630fc49c7a64

test:
  secret_key_base: 38070d17cd59207c2e18c8dd4234d798533b3509d0f642eeb2e338b1269a912d90fd56c2a7c7258ca15d670664467e7f2bfa55f296d6a94fe8a83f118a1eadf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
